import type { Metadata } from "next";
import "@bnext/ui/styles/layout/layout.scss";
import "@bnext/ui/styles/demo/Demos.scss";
import "primeicons/primeicons.css";
import "primeflex/primeflex.css";
import { PrimeReactProvider } from "primereact/api";
import { LayoutProvider } from "@bnext/context";


import "@bnext/ui/styles/lara-light-indigo/theme.css";
// import "@bnext/ui/styles/globals.css"

export const metadata: Metadata = {
  title: "Host App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const values = { ripple: true };
  return (
    <html lang="en">
      <body>
        <LayoutProvider>
          <PrimeReactProvider value={values}>{children}</PrimeReactProvider>
        </LayoutProvider>
      </body>
    </html>
  );
}
