import type { Metadata } from "next";
import "../styles/layout/layout.scss";
import "../styles/demo/Demos.scss";
import "primeicons/primeicons.css";
import "primeflex/primeflex.css";
import { PrimeReactProvider } from "primereact/api";

import "../styles/lara-light-indigo/theme.css";
// import "./globals.css";

export const metadata: Metadata = {
  title: "Host App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const values = { ripple: true };
  return (
    <html lang="en">
      <body>
        <PrimeReactProvider value={values}>{children}</PrimeReactProvider>
      </body>
    </html>
  );
}
